#!/usr/bin/php
<?php

/*
medials
List media files in a directory with media properties
Håvard Pedersen (fuzzy76)

TODO
- Filetype filtering (skip unknown files?)
- Filesize reporting
- Sort files (for now, pipe into sort)
- Intelligent tabulation
- Subtitle languages(?)
- Do not regard png as video
- Ignore folders
*/

$mf = new MediaFolder('.');
$mf->process();

class MediaFolder {
  public $found = array();
  function __construct($name) {
    if ($handle = opendir($name)) {
      while (false !== ($entry = readdir($handle))) {
        if (substr($entry,0,1) != '.' && (is_file($entry))) { // Only process visible files
          $this->found[] = $name . DIRECTORY_SEPARATOR . $entry;
        }
      }
      closedir($handle);
    }
  }

  function process() {
    foreach ($this->found as $file) {
      $mfile = new MediaFile($file);
      echo $mfile->singleLine();
    }
  }

  function __toString() {
    return print_r($this, TRUE);
  }

}


class MediaFile {
  public $fileinfo = '';
  public $filename;
  public $streams = array();
  function __construct($filename) {
    $run = "ffprobe -v quiet -print_format json -show_format -show_streams -show_error -select_streams u '$filename'";
    $fileinfo = shell_exec($run);
    $fileinfo = json_decode($fileinfo);
    $this->filename = basename($filename);
    $this->fileinfo = $fileinfo;
    if (count($fileinfo->streams)) {
      foreach($fileinfo->streams as $stream) {
        $newstream = new MediaStream($stream);
        $this->streams[] = $newstream;

      }
    }
  }

  function singleLine() {
    $vstreams = MediaFile::formatStreams($this->getStreams('video'));
    $astreams = MediaFile::formatStreams($this->getStreams('audio'));
    return sprintf("%-60.60s %10.10s %10.10s %20.20s %20.20s",$this->filename, $this->guessType(), $this->getContainer(), $vstreams, $astreams) . "\n";
  }

  function getContainer() {
    return $this->fileinfo->format->format_name;
  }

  function getStreams($filter) {
    if (!count($this->streams)) {
      return array();
    }
    $out = array();
    foreach($this->streams as $stream) {
      if ($stream->getType() == $filter) {
        $out[] = $stream;
      }
    }
    return $out;
  }

  function countStreams($filter) {
    if (!count($this->streams)) {
      return 0;
    }
    $out = 0;
    foreach($this->streams as $stream) {
      if ($stream->getType() == $filter) {
        $out++;
      }
    }
    return $out;
  }

  function guessType() {
    $container2type = array(
      'image2' => 'picture',
    );

    $container = $this->getContainer();
    if (isset($container2type[$container])) {
      return $container2type[$container];
    }

    if ($this->countStreams('video'))
      return 'video';

    if ($this->countStreams('audio'))
      return 'audio';

    return 'other';

  }

  static function formatStreams($streams) {
    $out = array();
    if (count($streams)) {
      foreach ($streams as $stream) {
        $bitrate = $stream->getBitrateFormatted();
        $out[] = $stream->getCodec() . ($bitrate ? "($bitrate)" : '');
      }
    }
    $out = implode(',', $out);
    return $out;
  }

  function __toString() {
    return print_r($this, TRUE);
  }

}

class MediaStream {
  public $streamdata = NULL;
  function __construct($stream) {
    $this->streamdata = $stream;
  }

  function getType() {
    // @todo We probably want to override the type here for some imageformats
    $codec = $this->getCodec();
    $codec2type = array(
      'image2' => 'picture',
    );
    if (isset($codec2type[$codec])) {
      return $codec2type[$codec];
    }
    return $this->streamdata->codec_type;
  }

  function getBitrateFormatted() {
    $number = $this->getBitrate();
    if (!$number)
      return NULL;
    $sz = 'BKMGTP';
    $factor = floor((strlen($number) - 1) / 3);
    $out = round($number / pow(1024, $factor), 1);
    $letter = ($factor ? @$sz[$factor] : ''); // Skip first letter
    if ($out == 0)
      echo $this;
    return "{$out} {$letter}b";
  }

  function getBitrate() {
    if (isset($this->streamdata->bit_rate))
      return $this->streamdata->bit_rate;
    if (isset($this->streamdata->max_bit_rate))
      return $this->streamdata->max_bit_rate;
    return NULL;
  }

  function getCodec() {
    return $this->streamdata->codec_name;
  }

  function __toString() {
    return print_r($this, TRUE);
  }
}

function errorout($text, $data = '') {
  echo "$text : $data\n";
}
